apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffmpeg-deployment
  labels:
    app: ffmpeg
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ffmpeg
  template:
    metadata:
      labels:
        app: ffmpeg
    spec:
      containers:
        - name: ffmpeg
          image: jrottenberg/ffmpeg:4.1-alpine
          resources:
            requests:
              cpu: "100m"
              memory: "15Mi"
            limits:
              cpu: "200m"
              memory: "30Mi"
          env:
            - name: FOLDER
              valueFrom:
                configMapKeyRef:
                  name: ffmpeg-config
                  key: stream.name
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: FFMPEG_PATH
              value: "/ffmpeg/chunks/$(FOLDER)"
            - name: SEGMENT_TIME
              valueFrom:
                configMapKeyRef:
                  name: ffmpeg-config
                  key: segment.time
            - name: FILE_FORMAT
              valueFrom:
                configMapKeyRef:
                  name: ffmpeg-config
                  key: file.format
            - name: STREAM
              valueFrom:
                configMapKeyRef:
                  name: ffmpeg-config
                  key: stream
          args:
            [
              "-y",
              "-i",
              "$(STREAM)",
              "-f",
              "segment",
              "-strftime",
              "1",
              "-segment_time",
              "$(SEGMENT_TIME)",
              "$(FFMPEG_PATH)/$(MY_POD_NAME)_$(FILE_FORMAT).mp3",
            ]
          volumeMounts:
            - name: ffmpeg-chunks
              mountPath: /ffmpeg/chunks
      # These containers are run during pod initialization
      initContainers:
        - name: folder
          image: busybox
          env:
            - name: FOLDER
              valueFrom:
                configMapKeyRef:
                  name: ffmpeg-config
                  key: stream.name
            - name: FFMPEG_PATH
              value: "/ffmpeg/chunks/$(FOLDER)"
          command:
            - mkdir
            - "-p"
            - "$(FFMPEG_PATH)"
          volumeMounts:
            - name: ffmpeg-chunks
              mountPath: /ffmpeg/chunks/
      volumes:
        - name: ffmpeg-chunks
          persistentVolumeClaim:
            claimName: ffmpeg-volume
