{{- if not (lookup "storage.k8s.io/v1" "StorageClass" "default" "azure-file-class") }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storageClass }}
  labels:
    {{- include "ffmpeg.labels" . | nindent 4 }}
provisioner: kubernetes.io/azure-file
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_LRS
{{- end }}